events {}

http {
    limit_req_zone $binary_remote_addr zone=local_public:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=local_login:10m rate=3r/m;
    limit_conn_zone $binary_remote_addr zone=local_conn:10m;

    upstream demo_app {
        server app:80;
    }

    server {
        listen 80;

        limit_conn local_conn 20;
        limit_req_status 429;

        location / {
            limit_req zone=local_public burst=20 nodelay;
            proxy_pass http://demo_app;
        }

        location /auth/login {
            limit_req zone=local_login burst=3 nodelay;
            proxy_pass http://demo_app;
        }
    }
}

